# Generated by Django 4.1.3 on 2023-03-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'logo', 'verbose_name_plural': 'logolar'},
        ),
    ]
