# Generated by Django 4.1.3 on 2023-03-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcha', '0003_logo_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bosh sahifa slaydi',
                'verbose_name_plural': 'Bosh sahifa slaydlari',
            },
        ),
    ]
