# Generated by Django 4.1.7 on 2023-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcha', '0004_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page',
            name='img_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
