# Generated by Django 4.1.7 on 2023-03-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcha', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='short_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
