# Generated by Django 4.1.7 on 2023-03-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcha', '0010_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
