# Generated by Django 4.1.7 on 2023-03-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcha', '0011_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
